In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int32')

In [4]:
a = np.array([1,2,3,4,'s'])
a

array(['1', '2', '3', '4', 's'], dtype='<U11')

In [5]:
a = np.append(a,5) # first aaray name then element that we want to add
a

array(['1', '2', '3', '4', 's', '5'], dtype='<U11')

In [6]:
a = np.append(a,[6,7,8,9]) # For adding multiple elements
a

array(['1', '2', '3', '4', 's', '5', '6', '7', '8', '9'], dtype='<U11')

In [7]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [10]:
a = np.arange(2,11,2)
a

array([ 2,  4,  6,  8, 10])

In [11]:
a.nbytes # for checking th memory space

20

In [12]:
a.itemsize # for checking each element size

4

In [13]:
len(a)

5

In [16]:
a = np.linspace(1,10,25)
a

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [17]:
a = np.logspace(1,10,20)
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [19]:
np.full(12,'a') # if we want to repeat any element

array(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'],
      dtype='<U1')

In [20]:
np.full(10,56)

array([56, 56, 56, 56, 56, 56, 56, 56, 56, 56])

In [23]:
np.ones(10) # If we want to repeat one in number of times.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones(10,dtype = int) # if we will mension dtype then we get integer format 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [28]:
a.ndim

1

## 2D arrays:

In [29]:
np.full((1,2),10) # one row and two columns the number is 10

array([[10, 10]])

In [30]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
b.ndim # For checking dimensions of the array

2

In [32]:
b.nbytes

48

In [33]:
b.itemsize

4

In [34]:
len(b) # This will return the numbe of rows as the length

3

In [35]:
b.size # this returns the total number of elements that b can hold

12

## 3D array:

In [40]:
c = np.array([[[1,2,3,4],[6,7,8,9]],[[3,4,5,6],[6,7,8,9]]])
c

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[3, 4, 5, 6],
        [6, 7, 8, 9]]])

In [41]:
c.ndim

3

In [42]:
len(c)

2

In [43]:
c.size

16

## Multidimensional arrays

In [44]:
d = np.array([1,2,3,4],ndmin = 5)
d

array([[[[[1, 2, 3, 4]]]]])

In [45]:
d.ndim

5

In [46]:
e = np.array([[1,2,3,4],[5,6,7,8]],ndmin = 10)
e

array([[[[[[[[[[1, 2, 3, 4],
               [5, 6, 7, 8]]]]]]]]]])

In [47]:
e.ndim

10

## Accessing of elements from the array:

### 1D array Accessing:

In [48]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
a[0] # for the first element

1

In [51]:
a[-1] # for the last element

7

In [52]:
a[:4] # this will gives us first 4 elements

array([1, 2, 3, 4])

### 2D ARRAY ACCESSING:

In [53]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
b[0] # this gives first row

array([1, 2, 3, 4])

In [55]:
b[-1] # returns last row

array([ 9, 10, 11, 12])

In [56]:
b[0,-1]

4

In [57]:
b[1:,-1]

array([ 8, 12])

In [58]:
b[:,-1]

array([ 4,  8, 12])

In [59]:
b[:,-2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### 3D array Accessing:

In [60]:
c

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[3, 4, 5, 6],
        [6, 7, 8, 9]]])

In [61]:
c[0]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [62]:
c[1]

array([[3, 4, 5, 6],
       [6, 7, 8, 9]])

In [63]:
c[0,0,0]

1

In [64]:
c[0,1]

array([6, 7, 8, 9])

In [65]:
c[1,1]

array([6, 7, 8, 9])

In [66]:
# first rows
c[:,0]

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [68]:
# both second rows
c[:,1]

array([[6, 7, 8, 9],
       [6, 7, 8, 9]])

In [69]:
c[:,:,-2]

array([[3, 8],
       [5, 8]])

## Shape of the arrays:

In [70]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [71]:
a.shape

(7,)

In [74]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
b.shape

(3, 4)

In [75]:
c

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[3, 4, 5, 6],
        [6, 7, 8, 9]]])

In [73]:
c.shape

(2, 2, 4)

### Reshaping of arrays:

- Changing the shape of the array and giving the new shape

In [76]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
## 1D array to 2D array:
ar = a.reshape(3,3) 

In [78]:
ar # converted array from 1d to 2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
ar = a.reshape(1,9)
ar

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
ar = a.reshape(9,1)

In [81]:

ar

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [82]:
### 1D to 3D array:

at = a.reshape(3,1,3)
at

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [83]:
at = a.reshape(3,3,1)
at

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [84]:
at = a.reshape(1,3,3)
at

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [85]:
at.ndim

3

In [86]:
af = a.reshape(1,3,3,1)
af

array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]])

In [87]:
af.ndim

4

In [88]:
af = a.reshape(3,1,3,1) # here we are converting 1d to 4d
af

array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]],


       [[[7],
         [8],
         [9]]]])

In [89]:
a.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
a.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
a.reshape(-1,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

## Iteration on arrays:

In [98]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [99]:
for i in l:
    print(i,end = " ")

1 2 3 4 

In [100]:
## 1D array iteration:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
for i in a:
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

In [102]:
## 2D array iteration:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
for i in b:
    for j in i:
        print(j,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [105]:
## 3D array iteration:
c

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[3, 4, 5, 6],
        [6, 7, 8, 9]]])

In [106]:
for i in c:
    for j in i:
        for k in j:
            print(k, end = " ")

1 2 3 4 6 7 8 9 3 4 5 6 6 7 8 9 

- This is all time taking process to take many for loops as dimensoin increase so we use other methods which are already in numpy and very helpful

### nditer

In [107]:
for i in np.nditer(c): 
    print(i,end = " ")

1 2 3 4 6 7 8 9 3 4 5 6 6 7 8 9 

In [108]:
for i in np.nditer(b):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

## Second Day

### Random Numbers in Numpy

In [1]:
import numpy as np

In [2]:
np.random.randint(50) # generate integers from 0 to 50

8

In [3]:
np.random.rand() # generate floating numbers between 0 to 1

0.9941699443097474

In [4]:
np.random.randint(10,100,size = (10)) # 1D array

array([76, 11, 45, 23, 10, 82, 40, 82, 76, 96])

In [5]:
np.random.randint(10,100,size = (3,4)) # 2D array

array([[81, 67, 26, 90],
       [81, 78, 23, 29],
       [55, 63, 25, 19]])

In [6]:
np.random.randint(10,100,size = (2,3,4)) #3D array

array([[[39, 79, 31, 34],
        [14, 21, 90, 81],
        [68, 12, 89, 79]],

       [[55, 64, 10, 59],
        [57, 27, 51, 63],
        [19, 50, 57, 11]]])

In [7]:
np.random.randint(10,100,size = (2,2,2,2,2))

array([[[[[32, 81],
          [31, 92]],

         [[95, 11],
          [41, 38]]],


        [[[33, 50],
          [43, 61]],

         [[45, 97],
          [94, 38]]]],



       [[[[93, 53],
          [83, 34]],

         [[33, 22],
          [37, 31]]],


        [[[15, 68],
          [69, 90]],

         [[89, 26],
          [37, 66]]]]])

In [15]:
 np.random.choice([10,12,9,200,6]) ## Choice of numbers.

10

In [19]:
np.random.choice([2,10,43,23,7,89],size = (3,4))

array([[10, 23,  2,  2],
       [89, 89, 10, 23],
       [ 7, 43,  7, 89]])

In [23]:
np.random.choice([13,21,45,23,6],p = [0.6,0,0.1,0.3,0]) # Here we are giving probability to each number so based on the probability only the numbers will be repeated

13

In [24]:
np.random.choice([13,21,45,23,6],p = [0.6,0,0.2,0,0.2],size = (3,3))

array([[45, 45, 13],
       [13, 13,  6],
       [ 6, 13, 13]])

In [29]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [30]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.random.shuffle(a)

In [32]:
a

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [33]:
# both negative and positives random numbers

np.random.randn(10)

array([ 0.57743804,  2.34114927,  1.26431873, -0.87674419,  0.59836264,
       -0.16382324, -1.91173243, -0.29502967, -1.05524031, -0.58336728])

In [38]:
# It will generate a binomial distribution number with probability 0.2
np.random.binomial(10,p = [0.2]) 

array([1])

In [42]:
np.random.normal()

1.26097528862511

## Array Filtering

In [43]:
a = np.array([10,20,30,40,13,12,56,98])
a

array([10, 20, 30, 40, 13, 12, 56, 98])

In [44]:
b = [True,True,False,True,False,True,False,False]

In [46]:
c = a[b]

In [47]:
c

array([10, 20, 40, 12])

In [49]:
## Create an array with elements greater than 15.
b = []
for i in a:
    if i >15:
        b.append(True)
    else:
        b.append(False)
print(b)
print(a[b])

[False, True, True, True, False, False, True, True]
[20 30 40 56 98]


In [50]:
d = a[a>15] # This is another way

In [51]:
d

array([20, 30, 40, 56, 98])

In [52]:
dot1 = np.arange(1,10.reshape(3,3))
dot2 = dot1
np.dot(dot1,dot2)

SyntaxError: invalid syntax (<ipython-input-52-09e629165b4f>, line 1)